[tasks]
test-frontend-unit = { dir = "frontend", run = ["npm run test:unit"] }
test-frontend-e2e = { dir = "frontend", run = ["npm run test:e2e"] }
test-cargo = "cargo test"

[tasks.test-e2e]
run = ["cargo build", "cargo run -p rhd_test{{arg(name='rhd_test_args', var=true, prefix=' -- ', required=false)}}"]

[tasks.test-all]
depends = ["test-frontend-unit", "test-frontend-e2e", "test-cargo", "test-e2e"]
