[tasks]

[tasks.test-cargo]
depends = ["cargo-build"]
run = ["cargo test"]

[tasks.cargo-build]
run = ["cargo build"]

[tasks.test-e2e]
depends = ["cargo-build"]
run = ["cargo run -p rhd_test{{arg(name='rhd_test_args', var=true, prefix=' -- ', required=false)}}"]

[tasks.test-all]
depends = ["test-cargo", "test-e2e"]

[tasks.cloc-backend]
run = ["cloc --vcs=git packages/"]

[tasks.cloc-memory]
run = ["cloc --vcs=git memory/"]

[tasks.cloc-plans]
run = ["cloc --vcs=git plans/"]

[tasks.cloc]
run = [
  "mise run cloc-backend",
  "mise run cloc-memory",
  "mise run cloc-plans",
]

[tasks.cloc-all]
run = ["cloc --vcs=git packages/ memory/ plans/"]

[tasks.check-cargo]
run = ["cargo check"]

[tasks.check]
depends = ["check-cargo"]

[tasks.top-files-backend]
run = ["find packages -name '*.rs' -type f -exec wc -l {} + | sort -rn | head -n 21"]

[tasks.check-large-files-backend]
run = ["find packages -name '*.rs' -type f -exec wc -l {} + | sort -rn | awk '$1 > 400 && $2 != \"total\" {print}'"]

[tasks.check-large-files]
depends = ["check-large-files-backend"]
